---

- name: "install basic packages"
  action: >
    {{ ansible_pkg_mgr }} name={{ packages_rhel }} state=latest update_cache=yes

- name: "amazon cloudwatch agent config from template"
  template:
    src: templates/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json.j2
    dest: "{{ cloudwatch_conf_json }}"
    owner: "{{ cloudwatch_user }}"
    group: "{{ cloudwatch_user_group }}"
    mode: 0755

- name: "amazon cloudwatch agent common config from template"
  template:
    src: templates/opt/aws/amazon-cloudwatch-agent/etc/common-config.toml.j2
    dest: "{{ cloudwatch_conf_toml }}"
    owner: "{{ cloudwatch_user }}"
    group: "{{ cloudwatch_user_group }}"
    mode: 0755

- name: restart amazon cloudwatch service
  service:
    enabled: true
    name: amazon-cloudwatch-agent
    state: "restarted"
